version: "3.2"

services:
  ru_de_checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ru_de_checker
    command: bash -l -c "cd /home/ru-de-faq && bash files/check.sh"
    volumes:
      - ../../.:/home/ru-de-faq
